services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
